from typing import TYPE_CHECKING, Any, Dict

from sqlalchemy import JSON, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.order import Order


class DishIngredient(Base, TimestampMixin):
    """Stores ingredients JSON generated by Groq (Planner Agent)."""
    __tablename__ = "dish_ingredients"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id", ondelete="CASCADE"),
        unique=True,
        index=True,
        nullable=False,
    )
    dish_name: Mapped[str] = mapped_column(String(150), nullable=False)
    ingredients: Mapped[Dict[str, Any]] = mapped_column(JSON, nullable=False)

    # Relationships
    order: Mapped["Order"] = relationship("Order", back_populates="dish_ingredient")
    dish_recipe: Mapped["DishRecipe"] = relationship(
        "DishRecipe", back_populates="dish_ingredient", uselist=False, cascade="all, delete-orphan"
    )


class DishRecipe(Base, TimestampMixin):
    """Stores cooking recipe steps JSON generated by Claude (Cook Agent)."""
    __tablename__ = "dish_recipes"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id", ondelete="CASCADE"),
        unique=True,
        index=True,
        nullable=False,
    )
    dish_ingredient_id: Mapped[int] = mapped_column(
        ForeignKey("dish_ingredients.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    dish_name: Mapped[str] = mapped_column(String(150), nullable=False)
    recipe: Mapped[Dict[str, Any]] = mapped_column(JSON, nullable=False)

    # Relationships
    order: Mapped["Order"] = relationship("Order", back_populates="dish_recipe")
    dish_ingredient: Mapped["DishIngredient"] = relationship("DishIngredient", back_populates="dish_recipe")
